// Generated by gir (https://github.com/gtk-rs/gir @ 350409c)
// from 
// from gir-files (./gir-files @ 38b7451)
// DO NOT EDIT

#[allow(unused_imports)]
use crate::auto::*;

pub type MoonLatitude = f64;
pub type MoonPhase = f64;
