// Generated by gir (https://github.com/gtk-rs/gir @ 350409c)
// from 
// from gir-files (./gir-files @ 38b7451)
// DO NOT EDIT

mod info;
pub use self::info::{Info};

mod location_entry;
pub use self::location_entry::{LocationEntry, NONE_LOCATION_ENTRY};

mod timezone_menu;
pub use self::timezone_menu::{TimezoneMenu, NONE_TIMEZONE_MENU};

mod alias;
pub use self::alias::MoonLatitude;
pub use self::alias::MoonPhase;

#[doc(hidden)]
pub mod traits {
    pub use super::location_entry::LocationEntryExt;
    pub use super::timezone_menu::TimezoneMenuExt;
}
