// Generated by gir (https://github.com/gtk-rs/gir @ 350409c)
// from .. (@ ???)
// from ../gir-files (@ 38b7451)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GWeatherConditionPhenomenon", sizeof(GWeatherConditionPhenomenon), alignof(GWeatherConditionPhenomenon));
    printf("%s;%zu;%zu\n", "GWeatherConditionQualifier", sizeof(GWeatherConditionQualifier), alignof(GWeatherConditionQualifier));
    printf("%s;%zu;%zu\n", "GWeatherConditions", sizeof(GWeatherConditions), alignof(GWeatherConditions));
    printf("%s;%zu;%zu\n", "GWeatherDistanceUnit", sizeof(GWeatherDistanceUnit), alignof(GWeatherDistanceUnit));
    printf("%s;%zu;%zu\n", "GWeatherFormatOptions", sizeof(GWeatherFormatOptions), alignof(GWeatherFormatOptions));
    printf("%s;%zu;%zu\n", "GWeatherInfoClass", sizeof(GWeatherInfoClass), alignof(GWeatherInfoClass));
    printf("%s;%zu;%zu\n", "GWeatherLocationEntry", sizeof(GWeatherLocationEntry), alignof(GWeatherLocationEntry));
    printf("%s;%zu;%zu\n", "GWeatherLocationEntryClass", sizeof(GWeatherLocationEntryClass), alignof(GWeatherLocationEntryClass));
    printf("%s;%zu;%zu\n", "GWeatherLocationLevel", sizeof(GWeatherLocationLevel), alignof(GWeatherLocationLevel));
    printf("%s;%zu;%zu\n", "GWeatherMoonLatitude", sizeof(GWeatherMoonLatitude), alignof(GWeatherMoonLatitude));
    printf("%s;%zu;%zu\n", "GWeatherMoonPhase", sizeof(GWeatherMoonPhase), alignof(GWeatherMoonPhase));
    printf("%s;%zu;%zu\n", "GWeatherPressureUnit", sizeof(GWeatherPressureUnit), alignof(GWeatherPressureUnit));
    printf("%s;%zu;%zu\n", "GWeatherProvider", sizeof(GWeatherProvider), alignof(GWeatherProvider));
    printf("%s;%zu;%zu\n", "GWeatherSky", sizeof(GWeatherSky), alignof(GWeatherSky));
    printf("%s;%zu;%zu\n", "GWeatherSpeedUnit", sizeof(GWeatherSpeedUnit), alignof(GWeatherSpeedUnit));
    printf("%s;%zu;%zu\n", "GWeatherTemperatureUnit", sizeof(GWeatherTemperatureUnit), alignof(GWeatherTemperatureUnit));
    printf("%s;%zu;%zu\n", "GWeatherTimezoneMenu", sizeof(GWeatherTimezoneMenu), alignof(GWeatherTimezoneMenu));
    printf("%s;%zu;%zu\n", "GWeatherTimezoneMenuClass", sizeof(GWeatherTimezoneMenuClass), alignof(GWeatherTimezoneMenuClass));
    printf("%s;%zu;%zu\n", "GWeatherWindDirection", sizeof(GWeatherWindDirection), alignof(GWeatherWindDirection));
    return 0;
}
